version: '3.7'

services:
  hackathon_db:
    image: mysql:latest
    container_name: hackathon_db
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: hackathon
      MYSQL_USER: bruno
      MYSQL_PASSWORD: bruno123
    ports:
      - 3306:3306
#    volumes:
#      - ./docker/db-data:/var/lib/mysql

  app:
    build: .
    container_name: hackathon_app
    depends_on:
      - hackathon_db
    ports:
      - 8080:8080